global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'laba-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']
    basic_auth:
      username: 'metrics'
      password: 'changeme'
